name: 'Run redpen with reviewdog'
description: '🐶Run redpen with reviewdog on pull requests to improve document writing experience.'
author: 'Tsuyoshi CHO <Tsuyoshi.CHO+develop@Gmail.com>'
inputs:
  github_token:
    description: 'GITHUB_TOKEN.'
    required: true
    default: ${{ github.token }}
  level:
    description: 'Report level for reviewdog [info,warning,error]'
    default: 'error'
  reporter:
    description: |
      Reporter of reviewdog command [github-check,github-pr-review].
      Default is github-pr-review.
      github-pr-review can use Markdown and add a link to rule page in reviewdog reports.
    default: 'github-pr-review'
  filter_mode:
    description: |
      Filtering mode for the reviewdog command [added,diff_context,file,nofilter].
      Default is added.
    default: 'added'
  fail_level:
    description: |
      Optional.  Exit code control for reviewdog, [none,any,info,warning,error]
      Default is `none`.
    default: 'none'
  fail_on_error:
    description: |
      Deprecated.

      Optional.  Exit code for reviewdog when errors are found [true,false]
      Default is `false`.

      If `true` is set, it will be interpreted as "-fail-level=error".
      But if "-fail-level" is set non-`none`, it will be ignored.
    default: 'false'
  reviewdog_flags:
    description: 'Additional reviewdog flags'
    default: ''
  basedir:
    description: "document basedir. Default: '.'"
    required: true
    default: '.'
  targets:
    description: "document files. Default: '*'"
    required: true
    default: '*'
  config:
    description: "config file path. Default(use redpen default rule): ''"
    required: true
    default: ''
  tool_name:
    description: 'Tool name to use for reviewdog reporter'
    default: 'redpen'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'alert-octagon'
  color: 'blue'
